apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2023-04-23T16:09:34Z"
  generation: 48
  name: helmapp
  namespace: argocd
  resourceVersion: "1551465"
  uid: b16127e7-bd52-4a3f-9765-6571d855e56f
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: first-app
    repoURL: https://pluhin.github.io/helm-23-23/
    targetRevision: 0.2.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health:
    status: Healthy
  history:
  - deployStartedAt: "2023-04-23T16:09:34Z"
    deployedAt: "2023-04-23T16:09:34Z"
    id: 0
    revision: 0.2.0
    source:
      chart: first-app
      repoURL: https://pluhin.github.io/helm-23-23/
      targetRevision: 0.2.0
  operationState:
    finishedAt: "2023-04-23T16:09:34Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: 0.2.0
    phase: Succeeded
    startedAt: "2023-04-23T16:09:34Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: PersistentVolumeClaim
        message: persistentvolumeclaim/helmapp-first-app-pvc created
        name: helmapp-first-app-pvc
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/helmapp-first-app created
        name: helmapp-first-app
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/helmapp-first-app created
        name: helmapp-first-app
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/helmapp-first-app created
        name: helmapp-first-app
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 0.2.0
      source:
        chart: first-app
        repoURL: https://pluhin.github.io/helm-23-23/
        targetRevision: 0.2.0
  reconciledAt: "2023-04-23T17:51:45Z"
  resources:
  - health:
      status: Healthy
    kind: PersistentVolumeClaim
    name: helmapp-first-app-pvc
    namespace: default
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: helmapp-first-app
    namespace: default
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: helmapp-first-app
    namespace: default
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: helmapp-first-app
    namespace: default
    status: Synced
    version: v1
  sourceType: Helm
  summary:
    externalURLs:
    - http://helm.k8s-20.sa/
    images:
    - eboraas/apache-php:latest
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        chart: first-app
        repoURL: https://pluhin.github.io/helm-23-23/
        targetRevision: 0.2.0
    revision: 0.2.0
    status: Synced
