apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd-helm
spec:
  destination:
    namespace: ci-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ci-cd
    repoURL: https://sorokatyie.github.io/helm/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
